gc-libgcrypt: fix build failure due to -Werror=suggest-attribute=const
Resovle the following build failure:
lib/gc-libgcrypt.c: In function 'gc_done':
lib/gc-libgcrypt.c:66:1: error: function might be candidate for attribute 'const' [-Werror=suggest-attribute=const]
 gc_done (void)
 ^~~~~~~
lib/gc-libgcrypt.c: In function 'gc_hash_digest_length':
lib/gc-libgcrypt.c:368:1: error: function might be candidate for attribute 'const' [-Werror=suggest-attribute=const]
 gc_hash_digest_length (Gc_hash hash)
 ^~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Jia Zhang <qianyue.zj@alibaba-inc.com>