Sync up error.c with glibc
This is a partial sync-up of error.c with glibc.  The following
changes went in:

- Get rid of the INTUSE macro
- Remove unused macro ALLOCA_LIMIT
- Fix a potential buffer overflow in error_tail (sourceware bz #15672)
- Fix a potential NULL dereference in strcmp

        error: Sync from glibc master
        * lib/error.c [_LIBC]: Remove INTUSE usage.
        (error_tail): Remove unused macro ALLOCA_LIMIT.
        Fix potential buffer overflow.  Fix potential NULL dereference
        in strcmp.