strerror: avoid warnings about discarding "const"
* lib/strerror.c (rpl_strerror): Instead of returning a const
string from each and every "case", use a variable, and add a single
cast after the switch.