strerror: simplify replacement
Only strerror-override depends on winsock2.h; our strerror.c file
does not.  This also fixes mingw strerror_r-posix use of winsock2.h
via strerror-override.

Since we assume C89 which guarantees a declaration for sterror, we
don't need to repeat that check.

* m4/strerror.m4 (gl_PREREQ_STRERROR): Delete.
* modules/strerror (configure.ac): No prereqs needed here...
* modules/strerror-override (configure.ac): ...but this needs it.
(Files): Add file for needed prereq macro.

Signed-off-by: Eric Blake <eblake@redhat.com>