perror: test for output mismatch
On IRIX 6.5, strerror(-1) returns NULL but perror("") for errno
of -1 prints "Unknown error"; POSIX requires that the two must
match, so we must replace perror.  But since IRIX also lacks
strerror_r, our probe for a working [__xpg_]strerror_r was
never even happening.

* m4/perror.m4 (gl_FUNC_PERROR): Add test, in order to replace
perror on IRIX.

Signed-off-by: Eric Blake <eblake@redhat.com>