error: avoid expand-before-require warning
* modules/errno (configure.ac): Require, rather than expand,
gl_HEADER_ERRNO_H.
* m4/errno_h.m4 (gl_HEADER_ERRNO_H_BODY): Merge...
(gl_HEADER_ERRNO_H): ...into this macro, and use AC_DEFUN_ONCE to
enforce that all clients require it.

Signed-off-by: Eric Blake <ebb9@byu.net>