test-getsockopt: avoid compiler warning
test-getsockopt.c: In function 'main':
test-getsockopt.c:48:5: warning: implicit declaration of function 'close' [-Wimplicit-function-declaration]

* tests/test-getsockopt.c (includes): Ensure close is declared.

Signed-off-by: Eric Blake <eblake@redhat.com>