nl_langinfo: fix build under mingw
The commit fcfce839 improved localization of names for week days
and months, but the author forget to include windows.h in order
to use 'GetACP ()'. Without this header file build using mingw
fails with this error message:

../../../gnulib/lib/nl_langinfo.c: In function 'ctype_codeset':
../../../gnulib/lib/nl_langinfo.c:76:5: warning: implicit declaration of
function 'GetACP' [-Wimplicit-function-declaration]
     sprintf (buf + 2, "%u", GetACP ());
     ^
In file included from
/usr/i686-w64-mingw32/sys-root/mingw/include/windows.h:73:0,
                 from ../../../gnulib/lib/nl_langinfo.c:149:
/usr/i686-w64-mingw32/sys-root/mingw/include/winnls.h: At top level:
/usr/i686-w64-mingw32/sys-root/mingw/include/winnls.h:653:64: error:
conflicting types for 'GetACP'
   WINBASEAPI UINT WINAPI GetACP(void);
                                                                ^
../../../gnulib/lib/nl_langinfo.c:76:29: note: previous implicit
declaration of 'GetACP' was here
     sprintf (buf + 2, "%u", GetACP ());
                             ^

Signed-off-by: Pavel Hrdina <phrdina@redhat.com>
Signed-off-by: Eric Blake <eblake@redhat.com>