gc-gnulib: fix several build failures due to -Werror=suggest-attribute=const
Resolve several build failures like this:
lib/gc-gnulib.c: In function 'gc_init':
lib/gc-gnulib.c:87:1: error: function might be candidate for attribute 'const' [-Werror=suggest-attribute=const]
 gc_init (void)
 ^~~~~~~

Signed-off-by: Jia Zhang <qianyue.zj@alibaba-inc.com>