error: use correct printf attributes on mingw
Now that we always turn on __USE_MINGW_ANSI_STDIO when extensions
are in use, we need to replicate the same logic in error.h as
we have in stdio.h, for selecting the correct format string that
will squelch gcc -Wformat=2 warnings.

Reported by Assaf Gordon.

* lib/stdio.in.h (_GL_ATTRIBUTE_SPEC_PRINTF): New define.

Signed-off-by: Eric Blake <eblake@redhat.com>