gc-libgcrypt: fix assignment error due to -Werror=pointer-sign
Resolve the following build failure:
lib/gc-libgcrypt.c: In function 'gc_hash_read':
lib/gc-libgcrypt.c:460:14: error: pointer targets in assignment differ in signedness [-Werror=pointer-sign]
       digest = gcry_md_read (ctx->gch, 0);
              ^

Signed-off-by: Jia Zhang <qianyue.zj@alibaba-inc.com>