strerror: Avoid "guessing no" when cross-compiling to glibc systems.
* m4/strerror.m4 (gl_FUNC_STRERROR): Require AC_CANONICAL_HOST. When
cross-compiling to a glibc platform, set gl_cv_func_working_strerror
to "guessing yes".
(gl_FUNC_STRERROR_0): Require AC_CANONICAL_HOST. When cross-compiling
to a glibc platform, set gl_cv_func_strerror_0_works to "guessing yes".